[package]
name = "eye_eier"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "~0.17", features = ["train", "cuda", "vision"] }
image = "0.25.6"
imageproc = "0.25.0"
serde = "1.0.219"
